AddEntity
Sky53/NewStorage pull request #1
Opened 2020-01-15 16:15 UTC by Sky53

2020-01-16 09:04 UTC, AkulovOleg requested changes

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.API/Storage.API.csproj
> +    <TargetFramework>netcoreapp3.0</TargetFramework>
Зачем версию понизил?

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.API/Startup.cs
> +                    context.RequestServices.GetService<StorageContext>();
Что это?

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.API/appsettings.json
> +  "Data": {
Зачем такую сложную структуру, оставь appsettings как был и просто добавь ConnectionString

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.API/libman.json
> +{
Что это за файл?

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.Business/Storage.Business.csproj
> +    <TargetFramework>netcoreapp3.0</TargetFramework>
версию всех проектов обратно, используй самый новый .net core

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.Business/Storage.Business.csproj
> +  <ItemGroup>
У тебя нет пока сервисов и репозиториев, зачем тебе это?

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Order.cs
> +        public User User { get; set; }
Он типа и CustomerId сам сгенерит в таблице?

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Order.cs
> +        public DateTime DateCreated { get; set; }
CreatedDate

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Product.cs
> +        public string SKU { get; set; }
Это должно быть PK, поэтому Id нам не нужен

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Product.cs
> +        public string NameProduct { get; set; }
Просто Name

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Product.cs
> +        public decimal Cost { get; set; }
Price

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Product.cs
> +        public Order Order { get; set; }
По твоей логике тут должен быть List<Order>

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.Domain/User.cs
> +        public string NameUser { get; set; }
Просто Name

2020-01-16 09:04 UTC, AkulovOleg commented on NewStorage/Storage.Domain/User.cs
> +        public DateTime DateOfBrith { get; set; }
Birthday

2020-01-16 13:11 UTC, Sky53 commented on NewStorage/Storage.API/Startup.cs
> +                    context.RequestServices.GetService<StorageContext>();
Получаю экземпляр StorageContext, Нужно для инициализации БД,

2020-01-16 13:39 UTC, Sky53 commented on NewStorage/Storage.API/appsettings.json
> +  "Data": {
Пи стандартной реализации appsettings вылетает Exp
InvalidOperationException: Configuration value 'Host=localhost;Port=5432;Database=StorageDB2;Username=postgres;Password=root' is not supported.

2020-01-16 13:40 UTC, Sky53 commented on NewStorage/Storage.API/libman.json
> +{
Вероятно создан IDE, осознанно не создавал

2020-01-16 13:40 UTC, AkulovOleg commented on NewStorage/Storage.API/appsettings.json
> +  "Data": {
Значит неправильно заполнил, как минимум кавычки должны быть двойными

2020-01-16 13:40 UTC, Sky53 commented on NewStorage/Storage.Business/Storage.Business.csproj
> +  <ItemGroup>
Поторопился с добавлением контроллеров

2020-01-16 13:41 UTC, AkulovOleg commented on NewStorage/Storage.API/Startup.cs
> +                    context.RequestServices.GetService<StorageContext>();
Не нужно)) ты его получаешь и ничего с ним не делаешь, какой смысл?

2020-01-16 13:41 UTC, AkulovOleg commented on NewStorage/Storage.API/libman.json
> +{
Удали, я не знаю что это

2020-01-16 13:41 UTC, Sky53 commented on NewStorage/Storage.Domain/Order.cs
> +        public User User { get; set; }
![image](https://user-images.githubusercontent.com/45273067/72529814-1571c100-387f-11ea-86e1-71eb6b411183.png)

2020-01-16 13:47 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Order.cs
> +        public User User { get; set; }
Прикол, сначала поправим всё по коду, потом запущу и буду смотреть

2020-01-17 13:36 UTC, AkulovOleg requested changes

2020-01-17 13:36 UTC, AkulovOleg commented on NewStorage/Storage.API/Startup.cs
> +                    context.RequestServices.GetService<StorageContext>();
Зачем ты это резолвнул, если ничего не поменял =)

2020-01-17 13:36 UTC, AkulovOleg commented on NewStorage/Storage.DAL/StorageContext.cs
> +           .HasOne(sc => sc.Order)
Сделай выравнивание кода по точкам

2020-01-17 13:36 UTC, AkulovOleg commented on NewStorage/Storage.DAL/StorageContext.cs
> +        public List<OrderProduct> OrderProduct { get; set; }
Что за List? Это DbSet тоже должен быть

2020-01-17 13:36 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Product.cs
> +        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
Я не уверен, что для товара SKU надо генерировать, обычно он в каком-то опред виде под конкретный магаз, поэтому этот PK будет задаваться руками

2020-01-17 15:37 UTC, Sky53 commented on NewStorage/Storage.API/Startup.cs
> +                    context.RequestServices.GetService<StorageContext>();
Проверяю инициализацию БД, и  этой строчкой у тебя автоматом создаться бд

2020-01-17 15:37 UTC, Sky53 commented on NewStorage/Storage.API/Startup.cs
> +                    context.RequestServices.GetService<StorageContext>();
Не боевое решение

2020-01-17 15:39 UTC, Sky53 commented on NewStorage/Storage.DAL/StorageContext.cs
> +        public List<OrderProduct> OrderProduct { get; set; }
Вот сейчас стыдно было

2020-01-17 15:40 UTC, Sky53 commented on NewStorage/Storage.Domain/Product.cs
> +        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
Identity проинициализирует ключ в БД, а так возможны коллизии же?

2020-01-20 20:52 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Product.cs
> +        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
Он тебе не даст вставить существующий ключ, ну вообще возможно sku было не самое лучше решение делать PK, но пока пофиг

2020-01-21 12:16 UTC, Sky53 commented on NewStorage/Storage.API/Startup.cs
> +                    context.RequestServices.GetService<StorageContext>();
Оставлю на этом этапе

2020-01-21 12:17 UTC, Sky53 commented on NewStorage/Storage.Domain/Product.cs
> +        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
Добавил ключ

2020-01-21 12:43 UTC, AkulovOleg requested changes

2020-01-21 12:43 UTC, AkulovOleg commented on NewStorage/Storage.Domain/User.cs
> +        public Guid Id { get; set; }
Зачем тут Guid?

2020-01-21 12:43 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Product.cs
> +        public Guid id { get; set; }
Давай везде int, смысл тут Guid?

2020-01-21 12:43 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Order.cs
> +        public List<OrderProduct> OrderProduct { get; set; }
Когда модель описываешь все свойства - которые описывают колонки сверху, а вот такие объекты после идут
+ между всеми свойствами во всех моделях добавь пустые строки

2020-01-21 12:43 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Order.cs
> +        public List<OrderProduct> OrderProduct { get; set; }
И название OrderProducts их там много

2020-01-21 12:43 UTC, AkulovOleg commented on NewStorage/Storage.Domain/Product.cs
> +        public List<OrderProduct> OrderProduct { get; set; }
Аналогично, перенести вниз и переименовать

2020-01-21 13:36 UTC, Sky53 commented on NewStorage/Storage.Domain/Product.cs
> +        public Guid id { get; set; }
Согласен,  Int будет на данной таске логичнее

2020-01-21 16:18 UTC, AkulovOleg requested changes

2020-01-21 16:18 UTC, AkulovOleg commented on NewStorage/Storage.API/Startup.cs
> +                    context.RequestServices.GetService<StorageContext>();
Убирай эту строку и давай мерджить

2020-01-21 16:20 UTC, AkulovOleg approved these changes

2020-01-21 16:20 UTC, merged