Generic repository
Sky53/NewStorage pull request #2
Opened 2020-01-22 10:11 UTC by Sky53

2020-01-23 07:47 UTC, AkulovOleg requested changes

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +    [Route("api/[controller]")]
пропиши норм роут сразу тут

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +    //serv/api/
удали

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        private IProductService _productService;
readonly

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        }
пустую строку после

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        }
пустую строку между методами

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        public Product GetAll()
Задача была только на Save, удали этот метод

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.API/Startup.cs
> +            app.UseHttpsRedirection();
Зачем нам это?

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.API/Startup.cs
>              });
пустая строка

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.API/Startup.cs
> +            services.AddMvc();
Мы MVC будем юзать?

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        public string AddProduct([FromBody]Product product)
Где у тебя DTO?

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.Business/IProductService.cs
> +        public string AddProduct(Product product);
пустые строки лучше между

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.Business/IProductService.cs
> +        public List<Product> GetProducts();
Эти нам не нужны сейчас

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.Business/ProductService.cs
> +                return "unsuccessfully";
Это что за пиздец?

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.Business/ProductService.cs
> +        public Product GetProduct()
убирай

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.DAL/Repository/ProductRepository.cs
> +        private StorageContext _context;
readonly

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.DAL/Repository/ProductRepository.cs
> +        private StorageContext _context;
+ пустая строка

2020-01-23 07:47 UTC, AkulovOleg commented on NewStorage/Storage.DAL/Repository/ProductRepository.cs
> +        public void Save(Product product)
Все методы должны быть асинхронные
Почитай про Task и async/await это важно
У EF есть методы SaveChangesAsync()

2020-01-23 14:09 UTC, Sky53 commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +    [Route("api/[controller]")]
Это я еще на первых парах писал себе подсказки

2020-01-23 14:11 UTC, Sky53 commented on NewStorage/Storage.API/Startup.cs
> +            app.UseHttpsRedirection();
Это я что-то тестил,

2020-01-23 14:14 UTC, Sky53 commented on NewStorage/Storage.Business/IProductService.cs
> +        public List<Product> GetProducts();
Я оставлю для проверки работоспособости, ок?

2020-01-23 14:14 UTC, Sky53 commented on NewStorage/Storage.Business/ProductService.cs
> +                return "unsuccessfully";
Это правда пиздец, не придумал ничего быстрее, что бы получать ответы от сервера

2020-01-23 14:19 UTC, AkulovOleg commented on NewStorage/Storage.Business/IProductService.cs
> +        public List<Product> GetProducts();
Неа, в базе смотри)

2020-01-23 14:19 UTC, AkulovOleg commented on NewStorage/Storage.Business/ProductService.cs
> +                return "unsuccessfully";
Тебе надо просто получить ОК или Не ОК, у тебя там если не ОК упадёт Exception, этого пока достаточно, можно его не обрабатывать даже

2020-01-27 10:46 UTC, AkulovOleg requested changes

2020-01-27 10:46 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +    [Route("api/[controller]")]
Так пропиши роут жёстко api/products

2020-01-27 10:46 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +            var product = _mapper.Map<Product>(productDTO);
перенести в бизнес

2020-01-27 10:46 UTC, AkulovOleg commented on NewStorage/Storage.Business/DTO/ProductDTO.cs
> +    public class ProductDTO
ProductRequest

2020-01-27 10:46 UTC, AkulovOleg commented on NewStorage/Storage.Business/DTO/ProductMapping.cs
> +
Зачем эти пустые строки?

2020-01-27 10:46 UTC, AkulovOleg commented on NewStorage/Storage.Business/IProductService.cs
> +
зачем пустая строка?

2020-01-27 10:46 UTC, AkulovOleg commented on NewStorage/Storage.Business/IProductService.cs
> +        public Task<int> AddProductAsync(Product product);
Принимать Dto тут

2020-01-27 10:46 UTC, AkulovOleg commented on NewStorage/Storage.DAL/Repository/ProductRepository.cs
> +            if (product != null)
`if(product == null)
{
 throw new Exception();
}`

Надо выходить из метода по наименьшему пути

2020-01-27 13:24 UTC, AkulovOleg commented
.vs в гитигнор надо добавить и удалить отсюда

2020-01-27 13:44 UTC, AkulovOleg requested changes

2020-01-27 13:44 UTC, AkulovOleg commented on NewStorage/Storage.Business/DTO/ProductRequest.cs
> +
remove

2020-01-27 13:44 UTC, AkulovOleg commented on NewStorage/Storage.Business/DTO/ProductRequest.cs
> +        public int id { get; set; }
Id

2020-01-27 13:44 UTC, AkulovOleg commented on NewStorage/Storage.DAL/Repository/ProductRepository.cs
> +
remove

2020-01-27 13:57 UTC, Sky53 commented on NewStorage/Storage.Business/DTO/ProductRequest.cs
> +        public int id { get; set; }
пока решили оставить же, не трогаю, позже переименую

2020-01-27 14:21 UTC, AkulovOleg approved these changes

2020-01-27 14:21 UTC, merged