Get up del
Sky53/NewStorage pull request #3
Opened 2020-01-27 15:30 UTC by Sky53

2020-01-27 17:51 UTC, AkulovOleg approved these changes
И я что-то не уследил, почему у тебя в ProductRequest вообще стоит Id?
Он автоматически генерироваться должен

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
Чисто на будущее, все файлы строятся по такой логике сначала все GET, потом все Post, потом PUT и потом DELETE
Аналогично в сервисах и репозиториях

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        [HttpDelete("{id:int}")]
первый раз вижу такую запись с типом, вообще достаточно просто {id}, он тип из типа переменной поймёт

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        public async Task<int> DeleteProduct(int id)
Зачем возвращать int?

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        public async Task<int> UpdateProduct([FromBody]ProductRequest productRequest)
Зачем возвращать int?

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +            return await _productService.FindProductAsyncById(id);
Это не find, это GetProductByIdAsync
В названии метода Async всегда в конце

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.Business/DTO/ProductResponse.cs
> +        public int id { get; set; }
В этом PR точно надо поменять на Id

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        public async Task<int> UpdateProduct([FromBody]ProductRequest productRequest)
Ты обновляешь конкретный продукт, поэтому у тебя обновление по id. Я бы сделал отдельно параметр из роута Id и из Body уже ProductRequest

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.Business/IProductService.cs
> +        public Task<int> UpdateProdctAsync(ProductRequest productRequest);
Product

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.Business/IProductService.cs
> +        public Task<int> DeleteProductAsync(int id);
В принципе т.к. это ProductService то нет смысла в названиях метода писать Product. Можно просто DeleteById ну или DeleteByIdAsync

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.Business/ProductService.cs
> +            var product = await _productRepository.FindByIdAsync(id);
GetByIdAsync

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.DAL/Repository/ProductRepository.cs
> +
Здесь как раз эта пустая строка не нужна)

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.DAL/Repository/ProductRepository.cs
> +            }
Пустая строка после

2020-01-27 17:51 UTC, AkulovOleg commented on NewStorage/Storage.DAL/Repository/ProductRepository.cs
> +            return product.Entity.id;
Нет смысла из Delete метода что-то возвращать

2020-01-27 17:51 UTC, AkulovOleg requested changes
miss click to approve, request changes

2020-01-28 07:25 UTC, Sky53 commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        public async Task<int> DeleteProduct(int id)
я хочу получать какую-то инфу по факту удаления, пока сделал так что получаю id удаленного элемента, вижу смысл переделать на булево значение

2020-01-28 07:26 UTC, Sky53 commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        [HttpDelete("{id:int}")]
тап при приведение типа типа не вылетает экзепшен, если мы пивысиди допустимые значения, невалидные данные просто не доходят до тела контроллера

2020-01-28 07:27 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        public async Task<int> DeleteProduct(int id)
Если не упало, значит удалилось. Потому что иначе SQL тебе ошибку кинет. Поэтому достаточно 200 ок вернуть

2020-01-28 07:27 UTC, Sky53 commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        public async Task<int> UpdateProduct([FromBody]ProductRequest productRequest)
аналогично получит результат выполнения, или Id или bool думаю можно возвращать

2020-01-28 07:44 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        public async Task<int> UpdateProduct([FromBody]ProductRequest productRequest)
Смотри ниже

2020-01-28 08:18 UTC, Sky53 commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +        public async Task<int> UpdateProduct([FromBody]ProductRequest productRequest)
Я подойду по этому просу

2020-01-28 09:33 UTC, Sky53 commented on NewStorage/Storage.Business/IProductService.cs
> +        public Task<int> UpdateProdctAsync(ProductRequest productRequest);
Сделал ProductResponse т.к. _productService возвращает данные в контроллер

2020-01-30 07:28 UTC, AkulovOleg requested changes

2020-01-30 07:28 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +            return await _productService.GetyIdAsync(id);
ById

2020-01-30 07:28 UTC, AkulovOleg commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +            var code = await _productService.DeleteAsync(id);
Что за код? Зачем он тут?

2020-01-30 07:28 UTC, AkulovOleg commented on NewStorage/Storage.Business/ProductService.cs
> +            return 200;
Это ужас, не надо так
Просто пусть Task возвращается без int

2020-01-30 07:28 UTC, AkulovOleg commented on NewStorage/Storage.DAL/Repository/ProductRepository.cs
> +            var productDelete = await _context.Products.FindAsync(id);
Тут можно сделать 1 запросом, достаточно просто создать:
 var product = new Product{ Id = id };
И передать его в метод Delete

2020-01-30 07:28 UTC, AkulovOleg commented on NewStorage/Storage.DAL/Repository/ProductRepository.cs
> +            var product = _context.Products.Remove(productDelete);
Зачем тут присвоение в product

2020-01-30 08:07 UTC, Sky53 commented on NewStorage/Storage.API/Controllers/ProductController.cs
> +            var code = await _productService.DeleteAsync(id);
Сделал просто Task

2020-01-30 08:15 UTC, Sky53 commented on NewStorage/Storage.DAL/Repository/ProductRepository.cs
> +            var product = _context.Products.Remove(productDelete);
Я изначально хотел возвращать удаляемый объект, public virtual EntityEntry<TEntity> 
Поскольку меня очень смущает пустое удаление

2020-01-30 14:36 UTC, AkulovOleg approved these changes

2020-01-30 14:36 UTC, merged